[versions]
kotlin = "1.9.10"

junit-jupiter = "5.9.3"

apache-commons-text = "1.10.0"

[libraries]
apache-commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "apache-commons-text" }

# Convention
gradle-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
gradle-convention = [
    "gradle-kotlin",
]

[plugins]

