[versions]
kotlin = "1.9.10"

junit-jupiter = "5.9.3"

[libraries]

# Convention
gradle-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
gradle-convention = [
    "gradle-kotlin",
]

[plugins]

